// <auto-generated />
using System;
using LineUpBot.Context.MatchDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LineUpBot.Migrations
{
    [DbContext(typeof(MatchLineUpDbContext))]
    [Migration("20260315095707_update_telegramGroup")]
    partial class update_telegramGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BotUserTelegramGroup", b =>
                {
                    b.Property<int>("BotUsersId")
                        .HasColumnType("integer");

                    b.Property<int>("TelegramGroupsId")
                        .HasColumnType("integer");

                    b.HasKey("BotUsersId", "TelegramGroupsId");

                    b.HasIndex("TelegramGroupsId");

                    b.ToTable("BotUserTelegramGroup");
                });

            modelBuilder.Entity("LineUpBot.Domain.Models.BotUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("NextCommand")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BotUsers");
                });

            modelBuilder.Entity("LineUpBot.Domain.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("PollId")
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TelegramGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TelegramGroupId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("LineUpBot.Domain.Models.SurveyBotUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("BotUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SurveyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BotUserId");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyBotUsers");
                });

            modelBuilder.Entity("LineUpBot.Domain.Models.TelegramGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TelegramGroupChatId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TelegramGroups");
                });

            modelBuilder.Entity("BotUserTelegramGroup", b =>
                {
                    b.HasOne("LineUpBot.Domain.Models.BotUser", null)
                        .WithMany()
                        .HasForeignKey("BotUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineUpBot.Domain.Models.TelegramGroup", null)
                        .WithMany()
                        .HasForeignKey("TelegramGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LineUpBot.Domain.Models.Survey", b =>
                {
                    b.HasOne("LineUpBot.Domain.Models.TelegramGroup", "TelegramGroup")
                        .WithMany("Surveys")
                        .HasForeignKey("TelegramGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramGroup");
                });

            modelBuilder.Entity("LineUpBot.Domain.Models.SurveyBotUser", b =>
                {
                    b.HasOne("LineUpBot.Domain.Models.BotUser", "BotUser")
                        .WithMany("SurveyUsers")
                        .HasForeignKey("BotUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineUpBot.Domain.Models.Survey", "Survey")
                        .WithMany("SurveyUsers")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BotUser");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("LineUpBot.Domain.Models.BotUser", b =>
                {
                    b.Navigation("SurveyUsers");
                });

            modelBuilder.Entity("LineUpBot.Domain.Models.Survey", b =>
                {
                    b.Navigation("SurveyUsers");
                });

            modelBuilder.Entity("LineUpBot.Domain.Models.TelegramGroup", b =>
                {
                    b.Navigation("Surveys");
                });
#pragma warning restore 612, 618
        }
    }
}
